docker-compose-yaml: docker-compose.yml

environments:
  master:
    types:
      mariadb: mariadb-shared
    cronjobs:
      - name: drush cron
        schedule: "0 * * * *"
        command: 'drush cron --root=/app'
        service: cli

# Note regarding tasks in the scaffold.
# Please avoid making scripts more than one or two lines, and avoid if/else logic.
# When PaaS users or the support team modify this file, it should be easy to turn things on and off.

tasks:
  # Pre-rollout tasks do not get called on first deploy; use post-rollout tasks instead.
  pre-rollout:
    - run:
        name: Pre-rollout database updates
        command: /app/vendor/bin/govcms-pre-deploy-update-database
        service: cli
        shell: bash
    - run:
        name: Snapshot the database and store
        command: /app/vendor/bin/govcms-backup-db
        service: cli
        shell: bash
    - run:
        name: Snapshot the config and store
        command: /app/vendor/bin/govcms-backup-config
        service: cli
        shell: bash

  post-rollout:
    - run:
        name: Prepare the site for deployment
        command: /app/vendor/bin/govcms-prepare
        service: cli
        shell: bash
    - run:
        name: Synchronise the database
        command: /app/vendor/bin/govcms-db-sync
        service: cli
        shell: bash
    - run:
        name: Perform database updates
        command: /app/vendor/bin/govcms-update-database
        service: cli
        shell: bash
    - run:
        name: Perform config import
        command: /app/vendor/bin/govcms-config-import
        service: cli
        shell: bash
    - run:
        name: Perform cache rebuild
        command: /app/vendor/bin/govcms-cache-rebuild
        service: cli
        shell: bash
    - run:
        name: Ensure GovCMS/Lagoon modules are enabled
        command: /app/vendor/bin/govcms-enable-modules
        service: cli
        shell: bash
    - run:
        name: Preserve the last successful backup
        command: /app/vendor/bin/govcms-preserve-backups
        service: cli
        shell: bash

